export const SECTION_META = {
  markdown: { icon: "mdi:clipboard-text-outline", title: "Solicitud y objetivo", accent: "#1e90ff" },
  md: { icon: "mdi:clipboard-text-outline", title: "Solicitud y objetivo", accent: "#1e90ff" },
  text: { icon: "mdi:clipboard-text-outline", title: "Solicitud y objetivo", accent: "#1e90ff" },
  table: { icon: "mdi:table-large", title: "Tabla", accent: "#6366f1" },
  code: { icon: "mdi:code-tags", title: "Código", accent: "#0ea5e9" },
  sql: { icon: "mdi:database-search-outline", title: "SQL", accent: "#0ea5e9" },
  image: { icon: "mdi:eye-outline", title: "Evidencia", accent: "#8b5cf6" },
  img: { icon: "mdi:eye-outline", title: "Evidencia", accent: "#8b5cf6" },
  url: { icon: "mdi:link-variant", title: "Enlaces", accent: "#14b8a6" },
  link: { icon: "mdi:link-variant", title: "Enlaces", accent: "#14b8a6" },
  accordion: { icon: "mdi:unfold-more-horizontal", title: "Detalle", accent: "#64748b" },
  "cambio-bd": { icon: "mdi:database-cog-outline", title: "Cambios en base de datos", accent: "#f59e0b" },
  cambios_bd: { icon: "mdi:database-cog-outline", title: "Cambios en base de datos", accent: "#f59e0b" },
  html: { icon: "mdi:file-document-outline", title: "Detalle", accent: "#64748b" },
  body: { icon: "mdi:file-document-outline", title: "Detalle", accent: "#64748b" },
};
